services:
  # Frontend React/Ionic app (development)
  app-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: build
    ports:
      - "5173:5173"
    depends_on:
      - backend-dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run dev

  # Backend Express server (development)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongo:27017/materialmanager
      - MONGODB_USER=root
      - MONGODB_PASSWORD=example
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # MongoDB database
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: root-db
    volumes:
      - ./db/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db

  # MongoDB admin interface
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

volumes:
  mongo_data:
